<?php

declare(strict_types=1);

namespace AirSlate\Tests\Unit\Components;

use AirSlate\Tests\Unit\BaseTestCase;
use Illuminate\Foundation\Http\Events\RequestHandled;
use Illuminate\Http\Response;

class HttpQueryCounterComponentTest extends BaseTestCase
{
    public function createApplication()
    {
        putenv('APP_RUNNING_IN_CONSOLE=false');
        $_ENV['APP_RUNNING_IN_CONSOLE'] = false;
        return parent::createApplication(); // TODO: Change the autogenerated stub
    }

    public function testSuccess()
    {
        $this->riseEventQueryExecuted();
        $request = request();
        $response = new Response('test content', 212);
        event(new RequestHandled($request, $response));
        $metrics = $this->datastub->getMetric('gauge', 'airslate.db.queries');

        $this->assertEquals(
            ['code' => $response->getStatusCode(), 'method' => $request->method()],
            $metrics[0]['tags']
        );

        $this->assertEquals(
            1, $metrics[0]['value']
        );
    }
}
