# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
    - image: pdffiller/circleci-php

    working_directory: ~/repo

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v2-dependencies-{{ checksum "composer.json" }}
        # fallback to using the latest cache if no exact match is found
        - v2-dependencies-

    - run: composer config --global github-oauth.github.com 817f827a65d8a27e80ccf49c24c1482d2627de46
    - run: composer install -n --prefer-dist --ignore-platform-reqs

    - save_cache:
        paths:
          - ./vendor
        key: v2-dependencies-{{ checksum "composer.json" }}

    # run tests!
    - run: ./vendor/bin/phpcs
    - run: ./vendor/bin/psalm --show-info=false
